<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Font\iconfont.ttf" />
    <None Remove="Assets\Font\YouSheBiaoTiHei.ttf" />
    <None Remove="Assets\Image\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Model\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Font\iconfont.ttf" />
    <Resource Include="Assets\Font\YouSheBiaoTiHei.ttf" />
    <Resource Include="Assets\Image\logo.png" />
  </ItemGroup>

</Project>
